package uw.star.rts.cost;

public enum PrecisionPredictionModel {
   RWPredictor,RWPredictor_RegressionTestsOnly,RWPredictor_multiChanges,RWPredictor_multiChanges2,
   RWPredictor_CombinesClassDependency,RWPredictor_RegressionTestsOnly_CombinesClassDependency,RWPredictor_multiChanges_CombinesClassDependency,RWPredictor_multiChanges2_CombinesClassDependency
}
